# Generated by Django 4.2 on 2023-05-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=50, verbose_name='contact name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('message', models.TextField(max_length=500, verbose_name='message')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
